server:
  port: 8080
spring:
  application:
    name: traces_mcp
  ai:
    mcp:
      server:
#        comment below for making server STDIO
        protocol: STREAMABLE
        enabled: true
        name: traces_mcp
        version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"

zipkin:
  url: http://tracing-server:9411