spring:
  application:
    name: opensearch_mcp
  ai:
    mcp:
      server:
#        comment below for making server STDIO
        protocol: STREAMABLE
        enabled: true
        name: opensearch_mcp
        version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
search:
  opensearch:
    index: logs*
    hostname: opensearch
    port: 9200
    scheme: http
server:
  port: 8080