server:
  port: 8085
spring:
  application:
    name: metrics_mcp
  ai:
    mcp:
      server:
#        comment below for making server STDIO
        protocol: STREAMABLE
        enabled: true
        name: metrics_mcp
        version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"

prometheus:
  url: http://prometheus:9090