{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "github-mcp-server.fullname" . }}
spec:
  host: {{ .Values.route.host | quote }}
  to:
    kind: Service
    name: {{ include "github-mcp-server.fullname" . }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: {{ .Values.route.tls.termination }}
{{- end }}
