apiVersion: v1
kind: Secret
metadata:
  name: github-mcp-secret
type: Opaque
stringData:
  github-token: {{ .Values.github.token | quote }}
  github-secret: {{ .Values.github.secret | quote }}
  github-client-id: {{ .Values.github.clientId | quote }}

---
{{- if .Values.docker.pat }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-mcp-server.fullname" . }}-registry
type: kubernetes.io/dockerconfigjson

{{- $repo := printf "%s" .Values.image.repository }}
{{- $registry := index (splitList "/" $repo) 0 }}

{{- $username := printf "%v" (default "USERNAME" .Values.docker.username) }}
{{- $email := printf "%v" (default "no-reply@example.com" .Values.docker.email) }}
{{- $password := printf "%v" .Values.docker.pat }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}

stringData:
  .dockerconfigjson: |
    {{ dict "auths" (dict $registry (dict
      "username" $username
      "password" .Values.docker.pat
      "email" $email
      "auth" $auth
    )) | toJson }}

{{- end }}