server:
  port: 8084

spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: deutschebank-aipocs
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro

    mcp:
      client:
        request-timeout: 180s
        streamable-http:
          connections:
            investigate_application_issue_mcp:
              url: http://localhost:8083
              endpoint: /mcp
agent:
  main:
    tool-names: investigate_logs,investigate_database,investigate_source_code,investigate_runtime,investigate_metrics,investigate_traces

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.tool: TRACE
    org.springframework.ai.chat.client: DEBUG
    org.springframework.ai.vertexai.gemini: DEBUG
    org.springframework.web.client: DEBUG