server:
  port: 8083

spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: deutschebank-aipocs
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro

    mcp:
      client:
        streamable-http:
          connections:
            server1:
              url: http://localhost:8080
              endpoint: /mcp