server:
  port: 8083

spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: deutschebank-aipocs
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro

    mcp:
      client:
        streamable-http:
          connections:
            opensearch-mcp:
              url: http://localhost:8080
              endpoint: /mcp
        # sse:
        #   connections:
        #     github-mcp:
        #      url: http://localhost:9601/mcp

        #      headers:
        #         Authorization: Bearer ${GITHUB_TOKEN}

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG
