apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

{{- range $app := .Values.applications }}
{{- if and $app.enabled $app.service $app.service.enabled }}
      - job_name: {{ $app.name }}
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - {{ $app.name }}:{{ $app.service.port }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config

data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /loki

      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules

      replication_factor: 1

      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      filesystem:
        directory: /loki/chunks

    limits_config:
      allow_structured_metadata: false

    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules

      rule_path: /tmp/loki/rules

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 5
        Log_Level info

    [INPUT]
        Name tail
        Path /logs/*.log
        Tag petclinic.*
        Read_from_Head true

    [FILTER]
        Name record_modifier
        Match petclinic.*
        Record pod ${POD_NAME}
        Record namespace ${POD_NAMESPACE}
        Record service ${SERVICE_NAME}

    [OUTPUT]
        Name opensearch
        Match petclinic.*
        Host opensearch
        Port 9200
        Index petclinic-logs
        Logstash_Format On
        Suppress_Type_Name On
        tls Off
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracemind-ui-nginx-config
data:
  default.conf: |
    location /api/ {
        proxy_pass http://trace-mind-agent:8080/api/;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_cache off;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        chunked_transfer_encoding off;
    }