{{- range .Values.applications }}
{{- $app := . }}
{{- if and $app.enabled $app.service $app.service.enabled $app.route $app.route.enabled }}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $app.name }}
  annotations:
    haproxy.router.openshift.io/timeout: 1h
spec:
  to:
    kind: Service
    name: {{ $app.name }}

  port:
    targetPort: {{ $app.service.port }}

  {{- if and $app.route.tls $app.route.tls.enabled }}
  tls:
    termination: edge
  {{- end }}

  {{- if $app.route.host }}
  host: {{ $app.route.host }}
  {{- end }}

---
{{- end }}
{{- end }}