{{- range .Values.applications }}
{{- if and .enabled .service .service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort | default .service.port }}
---
{{- end }}
{{- end }}